services:

  mysql-user:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./docker/volume_mysql_user:/var/lib/mysql
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user

  mysql-scooter:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes:
      - ./docker/volume_mysql_scooter:/var/lib/mysql
    container_name: mysql-scooter
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scooter

  mysql-travel:
    image: mysql:latest
    ports:
      - "3309:3306"
    volumes:
      - ./docker/volume_mysql_travel:/var/lib/mysql
    container_name: mysql-travel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel

  mysql-admin:
    image: mysql:latest
    ports:
      - "3310:3306"
    volumes:
      - ./docker/volume_mysql_admin:/var/lib/mysql
    container_name: mysql-admin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin

  mongodb-tariff:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-tariff
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tariff
    volumes:
      - ./docker/volume_mongo:/data/db
